# version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/development/php/Dockerfile
    container_name: union_banking_app
    restart: unless-stopped
    working_dir: /var/www/union_banking
    volumes:
      - ./:/var/www/union_banking
      - ./storage:/var/www/union_banking/storage
      - ./bootstrap/cache:/var/www/union_banking/bootstrap/cache
    environment:
      APP_ENV: local
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: union_banking
      DB_USERNAME: union_banking_user
      DB_PASSWORD: secret
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis
    networks:
      - union_banking_network

  # node:
  #   build:
  #     context: .
  #     dockerfile: docker/development/node/Dockerfile
  #   container_name: union_banking_node
  #   restart: unless-stopped
  #   working_dir: /var/www/union_banking
  #   volumes:
  #     - ./:/var/www/union_banking
  #     - node_modules:/var/www/union_banking/node_modules
  #   ports:
  #     - '5173:5173'
  #   networks:
  #     - union_banking_network
  #   command: sh -c "npm install && npm run build && npm run dev"

  nginx:
    image: nginx:alpine
    container_name: union_banking_nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/union_banking
      - ./docker/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - union_banking_network

  mysql:
    image: mysql:8.1
    container_name: union_banking_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: union_banking
      MYSQL_USER: union_banking_user
      MYSQL_PASSWORD: secret
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - union_banking_network

  redis:
    image: redis:alpine
    container_name: union_banking_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - union_banking_network

  scheduler:
    build:
      context: .
      dockerfile: docker/development/php/Dockerfile
    container_name: union_banking_scheduler
    restart: unless-stopped
    working_dir: /var/www/union_banking
    volumes:
      - ./:/var/www/union_banking
    command: php artisan schedule:work
    depends_on:
      - mysql
      - redis
    networks:
      - union_banking_network

  queue:
    build:
      context: .
      dockerfile: docker/development/php/Dockerfile
    container_name: union_banking_queue
    restart: unless-stopped
    working_dir: /var/www/union_banking
    volumes:
      - ./:/var/www/union_banking
    command: php artisan queue:work redis --sleep=3 --tries=3 --timeout=90
    depends_on:
      - mysql
      - redis
    networks:
      - union_banking_network

  horizon:
    build:
      context: .
      dockerfile: docker/development/php/Dockerfile
    container_name: union_banking_horizon
    restart: unless-stopped
    working_dir: /var/www/union_banking
    volumes:
      - ./:/var/www/union_banking
    command: php artisan horizon
    depends_on:
      - redis
      - mysql
    networks:
      - union_banking_network

networks:
  union_banking_network:
    driver: bridge

volumes:
  db_data:
  node_modules:
