# version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/development/php/Dockerfile
    container_name: ccuss_app
    restart: unless-stopped
    working_dir: /var/www/ccuss
    volumes:
      - ./:/var/www/ccuss
      - ./storage:/var/www/ccuss/storage
      - ./bootstrap/cache:/var/www/ccuss/bootstrap/cache
    environment:
      APP_ENV: local
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ccuss
      DB_USERNAME: ccuss_user
      DB_PASSWORD: secret
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis
    networks:
      - ccuss-network

  node:
    build:
      context: .
      dockerfile: docker/development/node/Dockerfile
    container_name: ccuss_node
    restart: unless-stopped
    working_dir: /var/www/ccuss
    volumes:
      - ./:/var/www/ccuss
      - node_modules:/var/www/ccuss/node_modules
    ports:
      - '5173:5173'
    networks:
      - ccuss-network
    # command: sh -c "npm install && npm run dev"

  nginx:
    image: nginx:alpine
    container_name: ccuss_nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/ccuss
      - ./docker/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - ccuss-network

  mysql:
    image: mysql:8.1
    container_name: ccuss_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ccuss
      MYSQL_USER: ccuss_user
      MYSQL_PASSWORD: secret
    ports:
      - '3307:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ccuss-network

  redis:
    image: redis:alpine
    container_name: ccuss_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - ccuss-network

  scheduler:
    build:
      context: .
      dockerfile: docker/development/php/Dockerfile
    container_name: ccuss_scheduler
    restart: unless-stopped
    working_dir: /var/www/ccuss
    volumes:
      - ./:/var/www/ccuss
    command: php artisan schedule:work
    depends_on:
      - mysql
      - redis
    networks:
      - ccuss-network

  queue:
    build:
      context: .
      dockerfile: docker/development/php/Dockerfile
    container_name: ccuss_queue
    restart: unless-stopped
    working_dir: /var/www/ccuss
    volumes:
      - ./:/var/www/ccuss
    command: php artisan queue:work redis --sleep=3 --tries=3 --timeout=90
    depends_on:
      - mysql
      - redis
    networks:
      - ccuss-network

  horizon:
    build:
      context: .
      dockerfile: docker/development/php/Dockerfile
    container_name: ccuss_horizon
    restart: unless-stopped
    working_dir: /var/www/ccuss
    volumes:
      - ./:/var/www/ccuss
    command: php artisan horizon
    depends_on:
      - redis
      - mysql
    networks:
      - ccuss-network

networks:
  ccuss-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
